import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { createServer } from 'http';
import { Server } from 'socket.io';
import dotenv from 'dotenv';
import connectDB from './config/database.js';
import authRoutes from './routes/auth.js';
import userRoutes from './routes/users.js';
import announcementRoutes from './routes/announcements.js';
import requestRoutes from './routes/requests.js';
import chatRoutes from './routes/chat.js';
import adminRoutes from './routes/admin.js';
import { setupSocket } from './sockets/socketHandler.js';
